#!/usr/bin/env python3

import sys
import codecs

CRLF = "\r\n"

def rot13():
    print("Status: 200 OK", "Content-Type: text/html; charset=utf-8", CRLF,
          sep=CRLF, end="")
    lines = [line.rstrip('\n') for line in sys.stdin]
    lines = [codecs.encode(line, "rot-13") for line in lines]

    for line in lines:
        print(line)

if __name__ == "__main__":
    rot13()
