#!/usr/bin/env zsh

if [ $# -lt 1 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 <file.req> [port=80] [ip=localhost]"
    return 1
fi

if [ -z "$2" ]; then
    2="80"
fi

if [ -z "$3" ]; then
    3="localhost"
fi

if ! [ -e "$1" ]; then
    echo "File does not exist"
    return 1
fi

if ! [ -s "$1" ]; then
    echo "Empty file"
    return 1
fi

echo "RUN: cat $1 | nc $3 $2"
echo "__________________________________________"
cat $1 | nc $3 $2
