#!/usr/bin/env zsh

# This script shall:
# Compare the status line of all request in sub-dir with the expected response

# ============================================================================ #
#                               Initialization                                 #
# ============================================================================ #

if [ "$SHLVL" = "1" ]; then
    source ./launch
fi

req_dir="requests_samples"

# ============================================================================ #
#                                   Begin                                      #
# ============================================================================ #

function check_all() {
    export SHLVL=1
    source ./launch

    if [ $# -lt 2 ]; then
        ft_exit "Usage: $0 <ip> <port> [methods_to_test]"
    elif [ $# -gt 2 ]; then
        test_methods=(${@: 3:$#})
    else
        test_methods=($(ls -d $req_dir/*/ | cut -d '/' -f 2))
    fi

    ip="$1"
    port="$2"
    rm -rf $www_path

    for method in ${test_methods[@]}; do
        if ! [ -d "${req_dir}/${method}" ]; then
            echo "Directory does not exist: $method"
            continue
        fi

        printf "${YELLOW}\t\t\t%s${EOC}\n" $method

        dir="${req_dir}/${method}"
        files=($(ls $dir/*.req))
        for file in ${files[@]}; do
            check_one $file $port $ip
        done

    done
}

if [ "$SHLVL" = "2" ]; then
    check_all $*
fi
