#!/usr/bin/env zsh

# This script shall:
# Compare the status line of all request in sub-dir with the expected response

# ============================================================================ #
#                               Initialization                                 #
# ============================================================================ #

export SHLVL=1
source ./launch

if [ $# -lt 2 ]; then
    ft_exit "Usage: $0 <ip> <port>"
elif [ $# -gt 2 ]; then
    test_protocols=(${@: 3:$#})
else
    test_protocols=(GET)
fi

req_dir="./requests_samples"

# ============================================================================ #
#                                   Begin                                      #
# ============================================================================ #

function check_all() {
    for protocol in ${test_protocols[@]}; do
        if ! [ -d "${req_dir}/${protocol}" ]; then
            echo "Directory does not exist: $protocol"
            continue
        fi

        echo $protocol
    done
}

check_all $1 $2
